# backend/Dockerfile
FROM node:20-slim

ENV NODE_ENV=production
WORKDIR /app

# Instala deps de producción
COPY package.json package-lock.json* ./
RUN npm ci --omit=dev

# Copia TODO el código (menos lo que ignore .dockerignore)
COPY . .

EXPOSE 8000
CMD ["node", "src/server.js"]
